language: php
php:
  - 7.0
git:
  lfs_skip_smudge: true
  
before_install:
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer config repositories.piripasa vcs https://github.com/piripasa/article-manager.git
  - composer require piripasa/article-manager dev-master
  - composer update
  - cp ./vendor/piripasa/article-manager/tests/config/.env ./
  - rm ./config/app.php
  - cp ./vendor/piripasa/article-manager/tests/config/app.php ./config
  - php artisan vendor:publish
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - php artisan migrate
  - cd ./vendor/piripasa/article-manager
  
script: "phpunit"

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true
